backend:
  branch: main
  name: github
  repo: RadioSnackTech/radiosnacktech.github.io
  base_url: https://netlify-oauth.jvns.ca
media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
site_url: https://radiosnack.ca
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "events"
    label: "Event"
    folder: "_data/events"
    create: true
    slug: "{{slug}}"
    extension: "json"
    format: "json"
    summary: "{{date | date('YYYY-MM-DD')}} - {{title}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Event URL", name: "url", widget: "string" }
  - name: "links"
    label: "Link"
    folder: "_data/links"
    create: true
    slug: "{{slug}}"
    extension: "json"
    format: "json"
    summary: "{{text}}"
    fields:
      - { label: "Text", name: "text", widget: "string" }
      - { label: "URL", name: "url", widget: "string" }
      - { label: "Icon", name: "icon_url", widget: "image", required: false }
  - name: "equipment"
    label: "Equipment"
    folder: "_data/equipment"
    create: true
    slug: "{{name | slug}}"
    extension: "json"
    format: "json"
    summary: "{{name}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image_url", widget: "image", required: false }
      - { label: "Image Alt Text", name: "image_alt_text", widget: "string" }
      - { label: "Requires training?", name: "requires_training", widget: "boolean", default: false }
